### PR TITLE
Symbol.iterator for Result

### LINKED ISSUE #12: Make Results Iterable
# ethjs-abi

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/ethjs/ethjs-abi/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/ethjs/ethjs-abi/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [ ] Bug (https://github.com/ethjs/ethjs-abi/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [X] Feature (https://github.com/ethjs/ethjs-abi/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

I'd love to have `Symbol.iterator` implemented on the [`Result`](https://github.com/ethjs/ethjs-abi/blob/master/src/index.js#L21) data structure. This would enable destructuring assignment, spreads, etc, when handling values returned from contracts. Additionally, iteration should only be performed over numerically indexed keys.

## Steps to reproduce

Using the [`decodeParams`](https://github.com/ethjs/ethjs-abi/blob/master/src/index.js#L69) function with any valid parameters, the following code will currently throw:

```js
const [a, b, c] = decodeParams(...);
```

Only the following works currently:

```js
const result = decodeParams(...);
const a = result[0]
const b = result[1]
const c = result[2]
```

# Versions

- Node/NPM: 8.6.0/yarn@1.1.0
- Browser: any

### PR DESCRIPTION
**Pull request by jozanza**
Added the `Symbol.iterator` method to instances of `Result`. If everyone's into it, I can write a couple test cases to keep coverage at 100%. Once merged, this would close #12.

### CODE REVIEW

**Comment by jozanza** [comment]
Looks like the webpack build failed. Does the UglifyJs plugin have something against generator function syntax? 🤔

**Comment by SilentCicero** [comment]
Possibly, I'm taking a week off, be back on the 13th.

This could be interesting!

**Comment by jozanza** [comment]
Enjoy your break!

**Comment by SilentCicero** [comment]
@jozanza can you look into another dev environment that would support your changes? Maybe switching out uglify JS, or looking into that more closely.

**Comment by jozanza** [comment]
@SilentCicero hey sorry for the delay. I updated the PR to use a non-generator iterator, so we shouldn't have to mess with the environment. Now, I just need to add a test to get coverage back up.

**Comment by kumavis** [comment]
@jozanza highly desired feature - seems like it needs some test coverage

**Pull request closed without merging**
